site_name: My Docs
theme: readthedocs

markdown_extensions:
  - admonition
  - grid_tables

pages:
  - Home: index.md
  - Base:
    - Partners: base/partners.md
    - PowerEmail: base/poweremail.md
    - Gestió ATR: base/atr.md
    - Gestió de polisses: base/polisses.md
    - Gestió de comptadors: base/comptadors.md
  - Distribuidora:
    - Inicio: distri/index.md
    - Telegestió: distri/telegestion.md
    - Contadors: distri/contadores.md
    - TPL: distri/tpl.md
    - CUPS: distri/cups.md
    - Pòlisses: distri/polizas.md
    - Facturació: distri/facturacion.md
    - Facturació:
      - Peatges: distri/facturacion_peajes.md
      - Contractació: distri/facturacion_contratacion.md
    - Administració Pública:
      - REE: distri/adm-pub/ree.md
      - CNMC: distri/adm-pub/cnmc.md
      - AEAT: distri/adm-pub/aeat.md
      - Gencat: distri/adm-pub/gencat.md
    - Perfils: distri/perfiles.md
    - GIS - Instalacions:
      - Subestacions: distri/subestaciones.md
      - CTS: distri/cts.md
      - CTS:
        - Cel·les i elements de tall: distri/celles.md
      - LAT: distri/lat.md
      - LBT: distri/lbt.md
      - Instalacions RE: distri/re.md
      - Expedients: distri/expedientes.md
      - Sincronització CUPS: distri/sincronizacion_cups.md
    - Calitat de servei: distri/calidad.md
  - Comercialitzadora:
    - Inici: comer/index.md
    - CUPS: comer/cups.md
    - Contractes: comer/contratos.md
    - Facturació: comer/facturacion.md
    - Gestió ATR: comer/switching.md
    - SIPS: comer/sips.md
    - Administració Pública:
      - CNMC: comer/adm-pub/cnmc.md
      - AEAT: comer/adm-pub/aeat.md
      - Gencat: comer/adm-pub/gencat.md
      - Informes: comer/adm-pub/informes.md
      - Tases Municipals: comer/adm-pub/municipal_taxes.md
  - Facturació:
    - Gestió de pagaments i cobraments: facturacio/cobraments.md
    - Gestió de lectures: facturacio/lectures.md
    - Lots: facturacio/lots.md
