site_name: PowERP Docs
theme: readthedocs

markdown_extensions:
  - admonition
  - grid_tables
  - markdown_blockdiag

pages:
  - Home: index.md
  - Base:
    - Partners: base/partners.md
    - PowerEmail: base/poweremail.md
    - Gestió ATR: base/atr.md
    - Atenció al Client: base/atc.md
    - Gestió de polisses: base/polisses.md
    - Gestió de comptadors: base/comptadors.md
  - Distribuidora:
    - Inicio: distri/index.md
    - Telegestió: distri/telegestion.md
    - Contadors: distri/contadores.md
    - Manual d'ús de TPL: distri/tpl.md
    - Manual d'ús de TPL:
      - Requeriments del sistema i instal·lació: distri/tpl/requeriments.md
      - Procés de treball: distri/tpl/proces_de_treball.md
      - Descàrrega electrònica de Tancaments i Curves: distri/tpl/decarrega_tancaments_i_curves.md
      - Fitxers d'intercanvi per GISCE-TPL: distri/tpl/intercanvi_tpl.md
      - Fitxers d'intercanvi entre GISCE-TPL i GISCE-ERP: distri/tpl/intercanvi_tpl_erp.md
    - CUPS: distri/cups.md
    - Pòlisses: distri/polizas.md
    - Facturació: distri/facturacion.md
    - Facturació:
      - Peatges: distri/facturacion_peajes.md
      - Règim especial: distri/facturacio_re.md
      - Contractació: distri/facturacion_contratacion.md
    - Administració Pública:
      - REE: distri/adm-pub/ree.md
      - CNMC: distri/adm-pub/cnmc.md
      - AEAT: distri/adm-pub/aeat.md
      - Gencat: distri/adm-pub/gencat.md
    - Perfils: distri/perfiles.md
    - GIS:
      - GIS Web: gis/websearch.md
      - Qgis: gis/qgis.md
      - Instalacions:
        - Subestacions: distri/subestaciones.md
        - CTS: distri/cts.md
        - CTS:
          - Cel·les i elements de tall: distri/celles.md
        - LAT: distri/lat.md
        - LBT: distri/lbt.md
        - Instalacions RE: distri/re.md
        - Expedients: distri/expedientes.md
        - Sincronització CUPS: distri/sincronizacion_cups.md
        - CINI - Generació Automàtica: distri/act_cinis.md
        - TI - Generació Automàtica: distri/act_tis.md
    - Qualitat de servei: distri/calidad.md
  - Comercialitzadora:
    - Inici: comer/index.md
    - CUPS: comer/cups.md
    - Contractes: comer/contratos.md
    - Facturació: comer/facturacion.md
    - Gestió ATR: comer/atr.md
    - SIPS: comer/sips.md
    - Administració Pública:
      - CNMC: comer/adm-pub/cnmc.md
      - AEAT: comer/adm-pub/aeat.md
      - Gencat: comer/adm-pub/gencat.md
      - Informes: comer/adm-pub/informes.md
      - Tases Municipals: comer/adm-pub/municipal_taxes.md
  - Facturació:
    - Validacions: facturacio/validacions.md
    - Gestió de canvi d'any: facturacio/canvi_any.md
    - Gestió de pagaments i cobraments: facturacio/cobraments.md
    - Gestió de lectures: facturacio/lectures.md
    - Lots: facturacio/lots.md
